/**
 * Data model for the Atlas.
 *
 * atlas.json is generated by the corpus-analysis pass (see scripts/atlas/):
 * every archived sketch gets a code-derived record (concepts, techniques,
 * forms, medium…), a vision record from its rendered thumbnail, and color
 * metrics; a synthesis pass adds named clusters, cross-series threads, and
 * opportunity insights. This module only types and derives — it never fetches.
 */

export type Vision = {
  bg: string;
  palette: string;
  hues: string[];
  density: string;
  composition: string[];
  texture: string[];
  energy: string;
  keywords: string[];
};

export type Metrics = {
  /** background hex sampled from the border */
  bg: string;
  bgL: number;
  meanL: number;
  meanC: number;
  /** fraction of pixels far from the background */
  ink: number;
  /** dominant OKLCH hue in degrees; null when achromatic */
  hue: number | null;
  hueShare: number;
  colors: string[];
};

export type AtlasNode = {
  id: string;
  name: string;
  /** directory key, e.g. "nalee/sketches"; null for root one-offs */
  series: string | null;
  /** display name, e.g. "nalee" */
  seriesLabel: string | null;
  /** YYYY-MM of first commit */
  date: string;
  /** YYYY-MM-DD of first commit */
  created: string;
  year: number;
  /** full-resolution Cloudinary URL */
  url: string;
  w: number;
  h: number;
  description: string;
  concepts: string[];
  techniques: string[];
  forms: string[];
  medium: string;
  motion: string;
  palette: string;
  influences: string[];
  system: string | null;
  notable: string | null;
  cluster: string;
  vision: Vision | null;
  metrics: Metrics | null;
};

export type Cluster = { key: string; name: string; blurb: string; count: number };

export type Thread = { key: string; name: string; note: string; members: string[] };

export type Insight = {
  kind: string;
  title: string;
  body: string;
  relatedIds: string[];
  tags: string[];
  clusterKeys?: string[];
};

export type TagField = 'concepts' | 'techniques' | 'forms';

export type AtlasData = {
  generatedAt: string;
  nodes: AtlasNode[];
  clusters: Cluster[];
  threads: Thread[];
  insights: Insight[];
  tagCounts: Record<TagField, [string, number][]>;
  /** cross-series similarity edges: [idA, idB, weight 0..1] */
  edges: [string, string, number][];
};

/** Base node width in world units; height follows the sketch's aspect. */
export const NODE_W = 64;

export const nodeH = (n: Pick<AtlasNode, 'w' | 'h'>) =>
  Math.round((NODE_W * n.h) / n.w);

/** Cloudinary transform for a sized thumb of the archived render. */
export const thumbUrl = (url: string, w: number) =>
  url.replace('/upload/', `/upload/w_${w},q_auto,f_auto/`);

export const runCommand = (id: string) => `VITE_SKETCH="${id}" npm run dev`;

/** Every-term substring match over the node's searchable text. */
export function matchesQuery(n: AtlasNode, query: string): boolean {
  const hay = [
    n.id,
    n.name,
    n.seriesLabel ?? '',
    n.description,
    n.cluster,
    n.medium,
    n.motion,
    n.palette,
    n.system ?? '',
    ...n.concepts,
    ...n.techniques,
    ...n.forms,
    ...n.influences,
    ...(n.vision?.keywords ?? []),
    ...(n.vision?.texture ?? []),
  ]
    .join(' ')
    .toLowerCase();
  return query
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .every((term) => hay.includes(term));
}

/** Does a node carry the given tag in the given field? */
export function hasTag(n: AtlasNode, field: TagField, tag: string): boolean {
  return n[field].includes(tag);
}
