import { defineConfig } from 'vite';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// The Atlas — local-only map of the whole body of work (`npm run atlas`).
// Dev server only: this config is never built and nothing under src/atlas/
// ships in dist/ or the deployed archive. Data comes from atlas.json at the
// workspace root (generated by the corpus-analysis pass; see AGENTS.md).
export default defineConfig({
  root: resolve(here, 'src/atlas'),
  plugins: [],
  server: {
    // Own port: 5173 = sketch runner, 5180 = Light Table, 5181 = Atlas.
    port: 5181,
    open: true,
    fs: {
      // atlas.json lives two levels above the vite root.
      allow: [resolve(here, '..')],
    },
  },
});
